# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: azure-desktop
description: microsoft maximalism

base-image: ghcr.io/butrejp/azure-coreos
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - inject-fedora-repos.sh

  - type: script
    scripts:
      - fix-fedora-repos.sh

  - type: dnf
    replace:
      - from-repo: fedora
        allow-erasing: true
        packages:
          - ostree

  - type: script
    scripts:
      - configure-dracut-ostree.sh

  - type: script
    scripts:
      - install-fedora-core.sh

  - type: dnf
    install:
      allow-erasing: true
      packages:
        - kernel
        - kernel-modules
        - kernel-modules-extra
        - gnome-shell
        - gdm

  - type: systemd
    system:
      enabled:
        - gdm.service

  - type: soar
  - type: signing