# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: azure-desktop
description: microsoft maximalism

base-image: ghcr.io/butrejp/azure-coreos
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # --- Install Fedora repos and keys via script ---
  - type: script
    scripts:
      - inject-fedora-repos.sh

  # --- Fix repo files for Azure Linux environment ---
  - type: script
    scripts:
      - fix-fedora-repos.sh

  # --- Install desktop packages from Fedora repos ---
  - type: dnf
    install:
      skip-unavailable: true
      allow-erasing: true
      packages:
        - dracut-ostree
        - gnome-shell
        - gdm

  - type: systemd
    system:
      enabled:
        - gdm.service

  - type: soar

  - type: signing
